### ISSUE TITLE
I found a bug in evaluation: performance can be doubled by simply duplicating the result txt

### ISSUE THREAD

**Issue by pansanity666** [VisDrone2018/VisDrone2018-MOT-toolkit#1]
For example, if the original mAP for Task4a is 35, after I duplicate the content of each video's txt file for 10 times, the mAP increases up to 65.

```

original txt:        after duplicated:
1,                            1,
2,                            2,
3,                            3,
                              1,
                              2,
                              3,
                              ...

```

The  bug lies in Line 182 - Line 204 in ```evaluateTrackA.m```. 
```
...
num_matched = 0;
num_total = length(union(img_ids, gt_img_ids));
for j = 1:num_obj
        ...
        if(ov >= gt_thr(k))
            num_matched = num_matched + 1;
        end
    end
end
ov = num_matched / num_total;
...
```

If the result txt is duplicated 10 times, `num_matched` will also be increased by 10 times, while num_total won't get larger since  `num_total = length(union(img_ids, gt_img_ids))` is a set operation. Thus, `ov` becomes larger, which leads to the improvement of mAP. 

In order to ensure the fairness of the challenge, an assertion should be added here to fix the bug.

**Comment by pansanity666** [comment]
I feel sorry that the organizer did not respond to this bug. They ignored my email, and, what's more, they deleted my question in the official website. 
Taking part in such an unfair challenge is a waste of time for me.

**Comment by VisDrone** [comment]
Thank you for pointing out the bug. We have fixed this issue.
