### ISSUE TITLE
Error in running task 4b Matlab2021b

### ISSUE THREAD

**Issue by sharoseali** [VisDrone2018/VisDrone2018-MOT-toolkit#2]
while running task 4b. I am getting following error:

```

Unrecognized function or variable 'clearMOTMex'. 
Error in CLEAR_MOT_HUN (line 50)
[mme, c, fp, m, g, d, alltracked, allfalsepos] = clearMOTMex(gtMat, resMat, threshold, world, VERBOSE);

Error in classEval (line 11)
        [metsCLEAR, ~, additionalInfo] = CLEAR_MOT_HUN(gtdata, resdata, threshold, world);

Error in evaluateTrackB (line 88)
    tendMets = classEval(gtsortdata, ressortdata, allMets, ind, evalClassSet, sequenceName);

Error in evalMOT (line 32)
     [tendallMets, allresult] = evaluateTrackB(seqPath, resPath, gtPath, evalClassSet);
 
>> 
```

**Comment by HeChengHui** [comment]
Hi, was wondering if you know how to get this toolkit to work? I am planning to test [DeepSORT w/ yolov5](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch) using VisDrone as a benchmark, but the example in the tracker folder has it in MatLab format, while my trackers are written in python.

**Comment by sharoseali** [comment]
You have to generate your tracker results in the form of text files as mentioned in Visdrone MOT web page. Put in one folder. In eval MOT.m change the path to your results folder  and Ground truth folder and run evalMOT.m.

**Comment by HeChengHui** [comment]
Thank you so much for the fast reply. I will give that a shot.

**Comment by HeChengHui** [comment]
@sharoseali 
Is there a place to get the detection input data? `detPath = '..\FasterRCNN-MOT-detections\test-challenge\'; % detection input path`

I am currently testing my tracker with VisDrone2019-MOT-test-challenge dataset which only has a sequence folder and no ground truth text files.

**Comment by sharoseali** [comment]
> @sharoseali Is there a place to get the detection input data? `detPath = '..\FasterRCNN-MOT-detections\test-challenge\'; % detection input path`
> 
> I am currently testing my tracker with VisDrone2019-MOT-test-challenge dataset which only has a sequence folder and no ground truth text files.

If you want to run a tracker either with task 4A or 4b then detection results don't matter. As you see in the code.

 `
if(strcmp(evalTask, 'Task4a'))
    [ap, recall, precision] = evaluateTrackA(seqPath, resPath, gtPath, evalClassSet)`

To evaluate tracker with 5 classes, i.e., car, bus, truck, pedestrian, and van. you can comment on this line. This function is for all 10 classes
`runTrackerAllClass(isSeqDisplay, isNMS, detPath, resPath, seqPath, evalClassSet, threSet, nmsThre, trackerName);`

For the test challenges, I think you cant evaluate your data using this toolkit. If you want to submit results on the leaderboard then you have to upload your results to the Visdrone team. They might evaluate your results

**Comment by HeChengHui** [comment]
Base on the last paragraph, it seems that this toolkit is only used for datasets with their annotation text files? like the validation set.
> Put in one folder. In eval MOT.m change the path to your results folder and Ground truth folder and run evalMOT.m.

Can I check which line is for the ground truth?

> To evaluate tracker with 5 classes, i.e., car, bus, truck, pedestrian, and van. you can comment on this line. This function is for all 10 classes
> `runTrackerAllClass(isSeqDisplay, isNMS, detPath, resPath, seqPath, evalClassSet, threSet, nmsThre, trackerName);`

Thanks for the heads up. I deleted the other classes besides 'pedestrian' since I am only interested in tracking people.

**Comment by sharoseali** [comment]
detPath is Ground Truths
By the way there is no problem to run tracker on all 5 classes. The tool results you individual mAP or MOTA for each class and Average mAP on all classes. So you can just consider pedestrian or people class from the results as in your case.

**Comment by HeChengHui** [comment]
I tried using a tracker with 2019 test-dev dataset.
`datasetPath `set to directory containing the annotation and sequence folder.
`detPath `set to the annotation folder.
`resPath `no change to path, but I copy-pasted the text inference results into that folder.

When I run evalMOT.m, it seems to also run the GOG tracker and I got the following error:
```
Index exceeds the number of array elements (1).

Error in runTrackerAllClass (line 24)
        idx = detections(:, 8) == classID & detections(:, 7) >= threSet(idClass);

Error in evalMOT (line 27)
runTrackerAllClass(isSeqDisplay, isNMS, detPath, resPath, seqPath, evalClassSet, threSet, nmsThre,
trackerName);
```

Am I suppose to comment out the line to run the tracker?
`% runTrackerAllClass(isSeqDisplay, isNMS, detPath, resPath, seqPath, evalClassSet, threSet, nmsThre, trackerName);`

**Comment by sharoseali** [comment]
> I tried using a tracker with 2019 test-dev dataset.
> `datasetPath `set to directory containing the annotation and sequence folder.
> `detPath `set to the annotation folder.
> `resPath `no change to path, but I copy-pasted the text inference results into that folder.

It's correct.



> When I run evalMOT.m, it seems to also run the GOG tracker and I got the following error:
> 
> ```
> Index exceeds the number of array elements (1).
> 
> Error in runTrackerAllClass (line 24)
>         idx = detections(:, 8) == classID & detections(:, 7) >= threSet(idClass);
> 
> Error in evalMOT (line 27)
> runTrackerAllClass(isSeqDisplay, isNMS, detPath, resPath, seqPath, evalClassSet, threSet, nmsThre,
> trackerName);
> ```
runTrackerAllClass is written to run results for 10 classes. I think you change the number of classes that's why the error occurs. As I said you can run the tracker on all 10 classes or with 5 classes using task 4A or 4B. You will get individual results for each class. So if you just want to get results on 1 class i-e pedestrian, you can run the tracker. It will result in you 0.0 mAP for other classes but for pedestrians, you should get mAP according to your results. For example when I run for only 5 classes using task A. I got individual AP as well as Average AP
```
`Category AP
car 3.89%
bus 2.41%
truck 3.54%
pedestrian 1.17%
van 5.43%
 - - - - - - - -
Mean AP: 3.29%
 = = = = = = = =
Mean AP@0.25: 6.12%
Mean AP@0.50: 2.33%
Mean AP@0.75: 1.42%
 = = = = = = = =`
```
 and make sure the Class Ids here starts from 1 to 10, not 0 to 9 so increment your object class ids by 1  if you are starting from 0

**Comment by HeChengHui** [comment]
Just to clarify, you did not put your tracker into the /tracker folder? Is your outcome only from the result text files?

> I think you change the number of classes that's why the error occurs

I didn't change that part of the code so it was still the 5 classes.

**Comment by sharoseali** [comment]
> 

No I didn't put my tracker and yes output comes from result files

**Comment by sharoseali** [comment]
> > 
> 
No I didn't put my tracker and yes output comes from result files
Ok then comment the line `runTrackerAllClass(isSeqDisplay, isNMS, detPath, resPath, seqPath, evalClassSet, threSet, nmsThre, trackerName); `
and set task.. check with both 4 A and B task

**Comment by HeChengHui** [comment]
Yeah only after commenting out that line does it work. Thanks for the help!

**Comment by HeChengHui** [comment]
@sharoseali 

Hi, did you happen to come across this error?

```
Error using evaluateTrackA (line 86)
Find inconsistent label in a track!

Error in evalMOT (line 31)
    [ap, recall, precision] = evaluateTrackA(seqPath, resPath, gtPath, evalClassSet);
```

**Comment by lebron-2016** [comment]
Hi, my code settings are as shown in the figure. Do you know why all the evaluation results are 0?
![image](https://user-images.githubusercontent.com/80045218/211503999-a951d39e-1c53-48dd-b297-77296f27dde7.png)
![image](https://user-images.githubusercontent.com/80045218/211504028-23ce8a48-ec81-4064-a38c-371836d8cdbe.png)
